#!/bin/tcsh -f
#
# 6/8/2015: JVS
#
#
# Setting home directory for the demo
set demoHome=../
#
# create short name for the executable
set particleDmlcDemo=$demoHome/particleDmlc++Demo/particleDmlc++Demo
#
# the .so's must be in your path----I will temporarily extend LD_LIBRARY_PATH 
# you should put the .so's wherever you keep other .so's
if !( $?UNAME ) setenv UNAME `uname -p`-$OSTYPE
setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:$demoHome/$UNAME
#
# the config files are expected to be in $UVA_DATA/dmlc, so set $UVA_DATA
setenv UVA_DATA $demoHome/uva/data
#
set samplePhsp=inputPhaseSpace.egsphsp1
#
#
# The file names tell which each type of dml file a file is
#
$particleDmlcDemo -dml fixedBeam.dml -ps $samplePhsp -z_plane 45 
printf "\n Hit enter to continue > "; set reply=$<
#
$particleDmlcDemo -dml stepAndShoot.dml -ps $samplePhsp -z_plane 45 
printf "\n Hit enter to continue > "; set reply=$<
#
$particleDmlcDemo -dml conformalArc.dml -ps $samplePhsp -z_plane 45 -oiaea -room 
printf "\n Hit enter to continue > "; set reply=$<
#
$particleDmlcDemo -dml smartArc.dml -ps $samplePhsp -z_plane 45 -oiaea -room
#
printf "\n $0 completed\n"
#
